type: list
store_sweep_json: true
groups:
  - type: list
    configs:
      - job.name: "qwen3_dense_8b_training_scale_nodes\\${slurm.sbatch.nodes}_mbsz\\${backend.megatron.micro_batch_size}_gbsz\\${backend.megatron.global_batch_size}_tp\\${backend.megatron.tensor_model_parallel_size}_fsdp\\${backend.megatron.use_torch_fsdp2}_num_workers\\${backend.megatron.num_workers}_leonardo"
        slurm.sbatch.nodes: 2
        backend.megatron.global_batch_size: 192
        backend.megatron.micro_batch_size: 6
        slurm.sbatch.qos: boost_qos_dbg
        backend.megatron.train_iters: 100
        slurm.sbatch.time: "00:30:00"
        # SCHEDULER
        backend.megatron.min_lr: 0.0
        backend.megatron.lr_warmup_iters: 20 # 2000 # Fixed for all.
        backend.megatron.lr_wsd_decay_iters: 0
        backend.megatron.eval_iters: 10
        backend.megatron.eval_interval: 99999999
