defaults:
  - base_llama
  - _self_

hidden_size: 4096
num_layers: 32
num_attention_heads: 32
group_query_attention: true
num_query_groups: 8
kv_channels: 128
ffn_hidden_size: 14336
seq_length: 4096
vocab_size: 50304
qk_layernorm: false
micro_batch_size: 1
tensor_model_parallel_size: 2
recompute_activations: false
recompute_granularity: selective
aux:
  model_name: "llama1.8bqkln"
