defaults:
 - _self_

### MODEL PARAMS for 600M Qwen3 model

# num_layers: 28
# hidden_size: 1024
# ffn_hidden_size: 3072
# num_attention_heads: 16
# group_query_attention: true
# num_query_groups: 8
# untie_embeddings_and_output_weights: false
# init_method_std: 0.02
# seq_length: 4096
# encoder_seq_length: null
# max_position_embeddings: 4096
# position_embedding_type: rope
# use_rotary_position_embeddings: true
# rotary_base: 10000
# rotary_percent: 1.0
# kv_channels: 128
# normalization: RMSNorm
# qk_layernorm: true
# attention_dropout: 0.0
# hidden_dropout: 0.0
# attention_softmax_in_fp32: true
# swiglu: true
# bf16: true
# add_bias_linear: false

### Model params for 150M Qwen3 model 

# num_layers: 12
# hidden_size: 768
# ffn_hidden_size: 2304
# num_attention_heads: 12
# group_query_attention: true
# num_query_groups: 12
# untie_embeddings_and_output_weights: false

# swiglu: true
# bf16: true
# attention_softmax_in_fp32: true
# use_rotary_position_embeddings: true
# rotary_base: 1000000
# rotary_percent: 1.0
# seq_length: 4096
# encoder_seq_length: null
# normalization: RMSNorm
# max_position_embeddings: 4096
# position_embedding_type: rope
# kv_channels: 128
# qk_layernorm: true
# attention_dropout: 0.0
# hidden_dropout: 0.0
# add_bias_linear: false
# use_flash_attn: true

init_method_std: 0.02

### DATA
global_batch_size: 512
data_path:
  - ${oc.env:DATA_DIR}/preprocessed/gpt-neox-20b/wikipesto/wikipesto
data_cache_path: ${job.base_output_dir}/cache
dataloader_type: single
num_workers: 7
tokenizer_type: HuggingFaceTokenizer
tokenizer_model: EleutherAI/gpt-neox-20b
make_vocab_size_divisible_by: 128
train_iters: 2384 # 
log_interval: 10
log_throughput: true
log_progress: true
log_timers_to_tensorboard: true
tensorboard_queue_size: 5
eval_iters: 100
eval_interval: 500
save_interval: 10000000
save: null
load: null



### OPTIMIZER
optimizer: adam
adam_beta1: 0.9
adam_beta2: 0.95
adam_eps: 1.0e-8
lr: 0.002
min_lr: 0.0
lr_decay_style: WSD
lr_wsd_decay_style: linear
lr_warmup_iters: ${oc.divi:${.train_iters},10}
lr_decay_iters: ${.train_iters}
lr_wsd_decay_iters: ${oc.divi:${.train_iters},5}
clip_grad: 1.0
weight_decay: 0.05