# MN5 speed test: real gpt-neox-20b tokenised data + local tokenizer.
defaults:
  - data_mn5
  - _self_

lr_warmup_iters: 0
train_iters: 500
save_interval: 1000000000
save: ${job.base_output_dir}
load: ${job.base_output_dir}
tensorboard_dir: ${job.base_output_dir}/tensorboard
