"""Autogenerated TorchTitan/Titan-OELLM config schema."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Literal

# NOTE: This file is generated. Do not edit by hand.


@dataclass
class Job:
    config_file: Any = None
    dump_folder: str = "./outputs"
    description: str = "default job"
    print_config: bool = False
    save_config_file: Any = None
    custom_config_module: str = ""
    continue_training: bool = False


@dataclass
class Profiling:
    enable_profiling: bool = False
    save_traces_folder: str = "profile_traces"
    profile_freq: int = 10
    profiler_active: int = 1
    profiler_warmup: int = 3
    enable_memory_snapshot: bool = False
    save_memory_snapshot_folder: str = "memory_snapshot"


@dataclass
class Metrics:
    log_freq: int = 10
    enable_tensorboard: bool = False
    disable_color_printing: bool = False
    save_tb_folder: str = "tb"
    save_for_all_ranks: bool = False
    enable_wandb: bool = False


@dataclass
class Model:
    name: str = "llama3"
    flavor: str = "debugmodel"
    hf_assets_path: str = "./tests/assets/tokenizer"
    tokenizer_path: str = ""
    converters: list[str] = field(default_factory=list)
    print_after_conversion: bool = False
    vocab_size: int = 50432
    mlp_layers: int = 2
    mlp_activation: str = "swiglu"
    qk_norm_type: str = "QKNormPlus"
    qk_norm_scale_mode: str = "scalar"
    tie_embedding: bool = False
    use_flex_attn: bool = False
    attn_mask_type: str = "causal"
    use_flash_attn: bool = False
    qk_norm: bool = True
    rope_theta: float = 1000000
    rope_scaling_factor: float = 8.0
    rope_low_freq_factor: float = 1.0
    rope_high_freq_factor: float = 4.0
    rope_original_max_position_embeddings: int = 8192
    head_dim: int = 128
    hidden_dim: int = 3072
    norm_eps: float = 1e-06
    depth_init: bool = True
    enable_weight_tying: bool = False
    moe_enabled: bool = False
    moe_inter_dim: int = 768
    dim: int = 768
    n_layers: int = 12
    n_heads: int = 6
    n_kv_heads: int = 6
    max_seq_len: int = 100000
    qkv_bias: bool = False
    mlp_bias: bool = False


@dataclass
class Optimizer:
    name: str = "AdamW"
    lr: float = 0.0008
    beta1: float = 0.9
    beta2: float = 0.95
    eps: float = 1e-08
    weight_decay: float = 0.1
    implementation: Literal["for-loop", "foreach", "fused"] = "fused"
    early_step_in_backward: bool = False


@dataclass
class LRScheduler:
    warmup_steps: int = 200
    decay_ratio: Any = None
    decay_type: Literal["linear", "sqrt", "cosine"] = "linear"
    min_lr_factor: float = 0.0
    scheduler_type: str = "wsd"
    stable_decay_ratio: float = 0.0
    lr_min_ratio: Any = None
    lr_min_absolute: Any = None
    warm_steps: int = 0
    warm_ratio: float = 0.0
    warm_direction: str = "up"
    warm_type: str = "linear"
    warm_start_ratio: float = 2.0
    main_decay_type: str = "const"
    main_decay_ratio: float = 0.2
    cooldown_steps: int = 0
    cooldown_ratio: float = 0.0
    cooldown_type: str = "cosine"
    lr_steps: Any = None


@dataclass
class DataLoader:
    num_workers: int = 0
    persistent_workers: bool = False
    pin_memory: bool = False
    prefetch_factor: Any = None


@dataclass
class Training:
    dataset: str = "c4_test"
    dataset_path: Any = None
    local_batch_size: int = 8
    global_batch_size: int = -1
    seq_len: int = 2048
    max_norm: Any = 1.0
    steps: int = 10000
    enable_cpu_offload: bool = False
    dtype: Literal["bfloat16", "float32"] = "float32"
    mixed_precision_param: Literal["bfloat16", "float32"] = "bfloat16"
    mixed_precision_reduce: Literal["float32"] = "float32"
    gc_freq: int = 50
    gc_debug: bool = False
    dataloader: DataLoader = field(default_factory=DataLoader)
    debug_moe_force_load_balance: bool = False


@dataclass
class Parallelism:
    data_parallel_replicate_degree: int = 1
    data_parallel_shard_degree: int = -1
    fsdp_reshard_after_forward: Literal["default", "always", "never"] = "default"
    tensor_parallel_degree: int = 1
    disable_loss_parallel: bool = False
    enable_async_tensor_parallel: bool = False
    pipeline_parallel_degree: int = 1
    module_fqns_per_model_part: Any = None
    pipeline_parallel_first_stage_less_layers: int = 1
    pipeline_parallel_last_stage_less_layers: int = 1
    pipeline_parallel_layers_per_stage: Any = None
    pipeline_parallel_schedule: str = "1F1B"
    pipeline_parallel_schedule_csv: Any = ""
    pipeline_parallel_microbatch_size: int = 1
    pipeline_parallel_expert_parallel_overlap: bool = True
    context_parallel_degree: int = 1
    context_parallel_rotate_method: Literal["allgather", "alltoall"] = "allgather"
    expert_parallel_degree: int = 1
    expert_tensor_parallel_degree: int = 1
    expert_parallel_comm_backend: Literal["standard", "deepep"] = "standard"
    enable_compiled_autograd: bool = False


@dataclass
class Checkpoint:
    enable: bool = False
    enable_ft_dataloader_checkpoints: bool = True
    folder: str = "checkpoint"
    interval: int = 500
    extra_steps: list[int] = field(default_factory=list)
    initial_load_path: Any = None
    initial_load_model_only: bool = True
    initial_load_in_hf: bool = False
    initial_load_in_hf_quantized: bool = False
    last_save_model_only: bool = True
    last_save_in_hf: bool = False
    export_dtype: Literal["float16", "bfloat16", "float32"] = "float32"
    async_mode: Literal["disabled", "async", "async_with_pinned_mem"] = "disabled"
    keep_latest_k: int = 10
    load_step: int = -1
    exclude_from_loading: list[str] = field(default_factory=list)
    enable_first_step_checkpoint: bool = False
    create_seed_checkpoint: bool = False
    load_only: bool = False


@dataclass
class ActivationCheckpoint:
    mode: Literal["selective", "full", "memory_budget", "none"] = "selective"
    selective_ac_option: str = "2"
    per_op_sac_force_recompute_mm_shapes_by_fqns: list[str] = field(
        default_factory=lambda: ["moe.router.gate"]
    )
    early_stop: bool = False
    memory_budget: float = 0.5
    visualize_memory_budget_pareto: bool = False
    preserve_rng_state: bool = False
    determinism_check: str = "default"
    debug: bool = False


@dataclass
class Compile:
    enable: bool = False
    components: list[str] = field(default_factory=lambda: ["model", "loss"])
    backend: str = "inductor"
    mode: Any = None


@dataclass
class Float8Linear:
    enable_fsdp_float8_all_gather: bool = False
    precompute_float8_dynamic_scale_for_fsdp: bool = False
    recipe_name: Literal["tensorwise", "rowwise", "rowwise_with_gw_hp"] | None = None
    filter_fqns: list[str] = field(default_factory=list)
    emulate: bool = False


@dataclass
class MXLinear:
    mxfp8_dim1_cast_kernel_choice: Literal["triton", "cuda", "torch"] = "triton"
    recipe_name: str = "mxfp8_cublas"
    filter_fqns: list[str] = field(default_factory=lambda: ["output"])


@dataclass
class QuantizedLinear:
    float8: Float8Linear = field(default_factory=Float8Linear)
    mx: MXLinear = field(default_factory=MXLinear)


@dataclass
class Float8GroupedMM:
    fqns: Any = field(default_factory=list)


@dataclass
class MXGroupedMM:
    recipe_name: Literal["mxfp8"] = "mxfp8"
    fqns: Any = field(default_factory=list)


@dataclass
class QuantizedGroupedMM:
    float8: Float8GroupedMM = field(default_factory=Float8GroupedMM)
    mx: MXGroupedMM = field(default_factory=MXGroupedMM)


@dataclass
class Quantize:
    linear: QuantizedLinear = field(default_factory=QuantizedLinear)
    grouped_mm: QuantizedGroupedMM = field(default_factory=QuantizedGroupedMM)


@dataclass
class Comm:
    init_timeout_seconds: int = 300
    train_timeout_seconds: int = 100
    trace_buf_size: int = 20000
    save_traces_folder: str = "comm_traces"
    save_traces_file_prefix: str = "rank_"
    mode: Literal["default", "fake_backend", "local_tensor"] = "default"


@dataclass
class MemoryEstimation:
    enable: bool = False
    disable_fake_mode: bool = False


@dataclass
class FaultTolerance:
    enable: bool = False
    process_group: str = "gloo"
    process_group_timeout_ms: int = 10000
    replica_id: int = 0
    group_size: int = 0
    min_replica_size: int = 1
    semi_sync_method: Any = None


@dataclass
class Experimental:
    custom_import: str = ""
    custom_args_module: str = ""


@dataclass
class ValidationDataset:
    name: str = ""
    data_prefix: Any = None
    local_batch_size: Any = None
    max_eval_samples: Any = None
    dataloader: Any = None
    data_source: Any = None
    split_samples: Any = None
    eval_mode: Any = None
    steps: Any = None
    best_fit_buffer_size: int = 500


@dataclass
class Validation:
    enable: bool = False
    freq: int = 100
    steps: int = -1
    data_prefix: str = ""
    local_batch_size: int = -1
    max_eval_samples: int = -1
    dataloader: str = "MMapDataset"
    data_source: str = "offline"
    split_samples: int = 0
    split_seed: int = 42
    eval_mode: str = "concatenated"
    datasets: list[ValidationDataset] = field(default_factory=list)


@dataclass
class Debug:
    seed: Any = None
    deterministic: bool = False
    deterministic_warn_only: bool = False
    moe_force_load_balance: bool = False


@dataclass
class SciData:
    local_batch_size: int = 8
    seq_len: int = 2048
    min_doc_len: int = 10
    data_prefix: Any = ""
    chunks_dir: Any = ""
    dataloader: str = "MMapDataset"
    seed: int = 42
    mask_eot_loss: bool = False


@dataclass
class SciTokenizer:
    default_add_bos: bool = True
    default_add_eos: bool = False
    override_hf_bos_behavior: bool = False
    override_hf_eos_behavior: bool = False


@dataclass
class ParameterLogging:
    enabled: bool = False
    log_interval: int = 100
    log_parameters: bool = True
    log_gradients: bool = True
    log_optimizer_states: bool = True
    log_gates: bool = False
    include_patterns: list[str] = field(default_factory=list)
    exclude_patterns: list[str] = field(default_factory=list)


@dataclass
class Benchmarks:
    enable: bool = True
    wikitext2_path: str = ""
    wikitext103_path: str = ""
    lambada_path: str = ""
    batch_size: int = 8


@dataclass
class JobConfig:
    class_name: str = "TitanJobConfig"
    job: Job = field(default_factory=Job)
    profiling: Profiling = field(default_factory=Profiling)
    metrics: Metrics = field(default_factory=Metrics)
    model: Model = field(default_factory=Model)
    optimizer: Optimizer = field(default_factory=Optimizer)
    lr_scheduler: LRScheduler = field(default_factory=LRScheduler)
    training: Training = field(default_factory=Training)
    parallelism: Parallelism = field(default_factory=Parallelism)
    checkpoint: Checkpoint = field(default_factory=Checkpoint)
    activation_checkpoint: ActivationCheckpoint = field(default_factory=ActivationCheckpoint)
    compile: Compile = field(default_factory=Compile)
    quantize: Quantize = field(default_factory=Quantize)
    comm: Comm = field(default_factory=Comm)
    memory_estimation: MemoryEstimation = field(default_factory=MemoryEstimation)
    fault_tolerance: FaultTolerance = field(default_factory=FaultTolerance)
    experimental: Experimental = field(default_factory=Experimental)
    validation: Validation = field(default_factory=Validation)
    debug: Debug = field(default_factory=Debug)
    data: SciData = field(default_factory=SciData)
    sci_tokenizer: SciTokenizer = field(default_factory=SciTokenizer)
    parameter_logging: ParameterLogging = field(default_factory=ParameterLogging)
    benchmarks: Benchmarks = field(default_factory=Benchmarks)
