#!/usr/bin/env python3.11
"""Build a Megatron blend spec for the multilingual MoE-metrics eval.

Takes the training data-mix (e.g. 1TT-option-4.sh, a flat 'weight path ...'
sequence over the openeurollm-tokenized-256k corpus) and remaps each source to
its counterpart in the held-out val corpus (openeurollm-tokenized-256k-val),
renormalizing over the sources that have a val counterpart. The result matches
the training sampling ratios and is consumed by:

  compute_moe_metrics.py --moe-data-type megatron_indexed \
      --moe-megatron-blend-file <this output>

Usage:
  python3.11 scripts/moe/build_multilingual_blend.py \
      [--datamix 1TT-option-4.sh] [--out scripts/moe/blends/multilingual_val_1TT_option4.sh]
"""
from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

TRAIN_ROOT = "/leonardo_work/OELLM_prod2026/preprocessed/openeurollm-tokenized-256k/"
VAL_ROOT = "/leonardo_work/OELLM_prod2026/preprocessed/openeurollm-tokenized-256k-val"
DEFAULT_DATAMIX = (
    "/leonardo_work/OELLM_prod2026/users/shaldar0/datamix_tools_from_fedor/"
    "datamix-tools/output/1TT-option-4.sh"
)
DEFAULT_OUT = "scripts/moe/blends/multilingual_val_1TT_option4.sh"

# opus-mt uses macrolanguage codes; the val nemotron-cc-opus set uses the
# individual-language codes for the same languages.
LANG_ALIAS = {"lav_Latn": "lvs_Latn", "est_Latn": "ekk_Latn"}


def remap(rel: str) -> str | None:
    """Map a training path (relative to TRAIN_ROOT) to a val prefix (relative
    to VAL_ROOT), or None if there is no sensible counterpart."""
    parts = rel.split("/")
    fam, lang = parts[0], parts[-1]
    lang_v = LANG_ALIAS.get(lang, lang)
    if fam == "finepdfs-10p-sample":
        return f"finepdfs/{lang_v}"
    if fam == "finepdfs-edu-10p-sample":
        return f"finepdfs-edu/{lang_v}"
    if fam == "hplt3-10p-sampled":
        return f"hplt3_sampled/{lang_v}"
    if fam == "tower9b":
        return f"multisynth-mt/tower9b/{lang_v}"
    if fam == "tower72b":
        return f"multisynth-mt/tower72b/{lang_v}"
    if fam == "opus-mt-10p-sample":
        return f"nemotron-cc-opus/{lang_v}_text_document"
    if fam == "dclm-baseline-1.0-10p-sample":
        return "dclm_merged"
    if fam == "nemotron-cc":
        m = {
            "nemotron-ha-10p-sample": "high-actual-merged",
            "nemotron-ma-10p-sample": "medium-actual-merged",
            "nemotron-mha-10p-sample": "medium-high-actual-merged",
        }
        return f"nemotron-cc/{m.get(lang, lang)}"
    if fam == "finemath-10p-sample":
        return "finemath-4plus"
    if fam == "LLM360":
        if "text-code-block" in lang:
            return "megamath-text-code-block"
        if "web-pro" in lang:
            return "megamath-web-pro"
    if fam == "OLMO-mix-10p-sample":
        if lang.startswith("arxiv"):
            return "arxiv"
        if lang.startswith("pes2o"):
            return "pes2o"
        if lang.startswith("Wiki"):
            return "Wiki"
    if fam == "starcoder-10p-sample":
        return "starcoder"
    return None


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--datamix", default=DEFAULT_DATAMIX)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--val-root", default=VAL_ROOT)
    args = ap.parse_args()

    toks = Path(args.datamix).read_text().split()
    if len(toks) % 2 != 0:
        raise SystemExit(f"datamix {args.datamix} has an odd token count")
    pairs = [(float(toks[i]), toks[i + 1]) for i in range(0, len(toks), 2)]

    kept: list[tuple[float, str]] = []
    dropped: list[tuple[float, str, str | None]] = []
    famcov: dict[str, list[float]] = defaultdict(lambda: [0.0, 0.0])
    for w, p in pairs:
        if not p.startswith(TRAIN_ROOT):
            raise SystemExit(f"unexpected training path: {p}")
        rel = p[len(TRAIN_ROOT):]
        fam = rel.split("/")[0]
        famcov[fam][1] += w
        vr = remap(rel)
        vp = f"{args.val_root}/{vr}" if vr else None
        if vp and Path(vp + ".idx").is_file() and Path(vp + ".bin").is_file():
            kept.append((w, vp))
            famcov[fam][0] += w
        else:
            dropped.append((w, rel, vr))

    total = sum(w for w, _ in kept)
    if total <= 0:
        raise SystemExit("no sources mapped to existing val files")

    header = [
        "# Multilingual val blend for MoE-metrics eval (compute_moe_metrics.py",
        "# --moe-megatron-blend-file). Auto-generated by build_multilingual_blend.py.",
        f"# Source data-mix: {args.datamix}",
        f"# Val corpus:      {args.val_root}",
        f"# {len(kept)}/{len(pairs)} sources mapped; "
        f"{100 * total:.2f}% of training weight covered; weights renormalized to 1.0.",
        "# Format: alternating 'weight path' pairs (Megatron blend spec).",
        "",
    ]
    body = [f"{w / total:.8f} {path}" for w, path in kept]
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text("\n".join(header + body) + "\n")

    print(f"Wrote {args.out}")
    print(f"  {len(kept)} sources kept, {len(dropped)} dropped")
    print(f"  covered {100 * total:.2f}% of training weight; renorm sum = "
          f"{sum(w / total for w, _ in kept):.6f}")
    print("  per-family coverage (kept_w / total_w):")
    for fam, (kw, tw) in sorted(famcov.items(), key=lambda x: -x[1][1]):
        print(f"    {fam:32s} {kw:.4f} / {tw:.4f}  ({100 * kw / tw:.0f}%)")
    if dropped:
        print("  dropped:")
        for w, rel, vr in sorted(dropped, key=lambda x: -x[0]):
            print(f"    w={w:.6f}  {rel} -> {vr}")


if __name__ == "__main__":
    main()
