defaults:
  - base
  - _self_

template_path: "templates/jupiter.sbatch"
launcher_cmd: "\
  export LOCAL_ADDR=$(nslookup $(hostname) | grep \"Address: \" | sed \"s/Address: //\" | tail) ;\\\n \
  ${oc.select:container.runtime,apptainer} exec \
  ${oc.join:' ',${oc.mapkeyvaltmpl:'--env %k=%v \\\n',${backend.env}}} \
  --writable-tmpfs --nv ${oc.join:' ',${oc.maptmpl:'--bind % \\\n',${container.bind}}} ${oc.select:container.image,container.sif} \\\n"
srun:
  exclusive: true
  wait: 60
  cpus_per_task: 288
launcher_env_passthrough: true
env:
  MACHINE_NAME: JUPITER
  HF_ALLOW_CODE_EVAL: "1"
  HF_DATASETS_OFFLINE: "1"
  TRANSFORMERS_OFFLINE: "1"
  MASTER_HOST: "$(scontrol show hostnames \"$SLURM_JOB_NODELIST\" | sed -n '1p')"
  MASTER_ADDR: "$(getent ahostsv4 \"$MASTER_HOST\" | sed -n '1{s/[[:space:]].*//;p;}')"
  MASTER_PORT: "20074"
  NUM_NODES: "$SLURM_JOB_NUM_NODES"
  GPUS_PER_NODE: "4"
  NUM_GPUS_PER_NODE: "4"
  NUM_GPUS: "$((NUM_GPUS_PER_NODE*SLURM_NNODES))"
  ARCH: "$(uname -m)"
  SLURM_ARRAY_TASK_ID: "$SLURM_ARRAY_TASK_ID"
  NCCL_SOCKET_IFNAME: ib0
  NCCL_SOCKET_FAMILY: AF_INET
  GLOO_SOCKET_IFNAME: ib0
  GLOO_SOCKET_FAMILY: AF_INET
  OMP_NUM_THREADS: 64

sbatch:
  nodes: 1
  ntasks_per_node: 1
  ntasks: ${.nodes}
  gpus_per_node: 4
  cpus_per_task: 288
  exclusive: true
  gpu_bind: "none"
  partition: ${oc.env:SLURM_PARTITION,booster}
  account: ${oc.env:SLURM_ACCOUNT,e-sta-openeurollm}
  time: "12:00:00"
