defaults:
  - base
  - _self_

template_path: "templates/jupiter.sbatch"
launcher_cmd: "\
  export LOCAL_ADDR=$(nslookup $(hostname) | grep \"Address: \" | sed \"s/Address: //\" | tail) ;\\\n \
  ${oc.select:container.runtime,apptainer} exec \
  ${oc.join:' ',${oc.mapkeyvaltmpl:'--env %k=%v \\\n',${backend.env}}} \
  --writable-tmpfs --nv ${oc.join:' ',${oc.maptmpl:'--bind % \\\n',${container.bind}}} ${oc.select:container.image,container.sif} \\\n"
srun:
  exclusive: true
  wait: 60
  cpus_per_task: 228
  threads_per_core: 1
launcher_env_passthrough: false
env:
  MACHINE_NAME: JUPITER
  MASTER_ADDR: "$(scontrol show hostnames \"$SLURM_JOB_NODELIST\" | head -n 1)"
  MASTER_PORT: "20074"
  ARCH: "$(uname -m)"
  NCCL_SOCKET_IFNAME: "ib0" # Force InfiniBand
  GLOO_SOCKET_IFNAME: "ib0"
  NCCL_SOCKET_FAMILY: "AF_INET" # Force IPv4

sbatch:
  nodes: 1
  ntasks_per_node: 1
  gpus_per_node: 4
  gres: "gpu:4"
  cpus_per_task: 228
  partition: ${oc.env:SLURM_PARTITION,booster}
  account: ${oc.env:SLURM_ACCOUNT,e-sta-openeurollm}
  time: "12:00:00"
