class_name: Container
image: ${oc.env:CONTAINER_CACHE_DIR,.}/titan_0.2.1_aarch64_202603131435.sif
runtime: apptainer
bind: ['/e']
env:
  WANDB_MODE: "offline"
  MACHINE_NAME: "JUPITER"
  PYTHONPATH: "."
python: "/usr/bin/python"
