class_name: Container
image: ${oc.env:CONTAINER_CACHE_DIR}/MegatronTraining-JUPITER_aarch64_202603120039.sif
runtime: apptainer
bind:
  - "/e"
env:
  WANDB_MODE: "offline"
  MACHINE_NAME: "JUPITER"
python: "python3"
