class_name: Container
image: /scratch/project_465002530/containers/AutoExp_2026-07-02.sif
runtime: singularity
bind:
  [
    "/boot/config-6.4.0-150600.23.73_15.0.14-cray_shasta_c",
    "/pfs/",
    "${oc.env:PWD}",
    "/scratch/",
    "/flash/",
  ]
pwd: ${oc.env:PWD}
env:
  WANDB_MODE: "offline"
  MACHINE_NAME: "LUMI"
  PYTHONPATH: "."
python: "python3"
