class_name: Container
# image: /scratch/project_462001516/users/swagatam/containers/AutoExp_2026-07-02.sif
# image: /pfs/lustref1/appl/local/laifs/containers/lumi-multitorch-u24r70f21m50t210-20260807_115122/lumi-multitorch-full-u24r70f21m50t210-20260807_115122.sif
image: /appl/local/laifs/containers/lumi-multitorch-u24r70f21m50t210-20260807_115122/lumi-multitorch-plus-u24r70f21m50t210-20260807_115122.sif
runtime: singularity
bind:
  [
    "/boot/config-6.4.0-150600.23.73_15.0.14-cray_shasta_c",
    "/pfs/",
    "${oc.env:PWD}",
    "/scratch/project_462001516/users/rluukkon/rccl-tuner",
    "/scratch/",
    "/flash/",
  ]
pwd: ${oc.env:PWD}
env:
  WANDB_MODE: "online"
  MACHINE_NAME: "LUMI"
  PYTHONPATH: "."

python: "python3"
