class_name: Container
image: ${oc.env:CONTAINER_CACHE_DIR}/untested/MegatronTrainingLumi_x86_64.sif
runtime: singularity
bind:
  [
    "/boot/config-6.4.0-150600.23.73_15.0.14-cray_shasta_c",
    "/pfs/",
    "${oc.env:PWD}",
    "/scratch/",
    "/flash/",
    "/opt/cray/pe/lmod/"
  ]
pwd: ${oc.env:PWD}
env:
  MACHINE_NAME: "LUMI"
  PYTHONPATH: "."
python: "python3"
