"""Resume timed-out or failed STABLE jobs from their last checkpoint.

When SLURM jobs hit the time limit (e.g. 24h), they exit with "DUE TO TIME LIMIT".
Megatron saves checkpoints periodically, so you can resume from the last one.

NOTE: Only stable-stage jobs can be resumed this way. Decay jobs (decay80BT,
decay120BT) depend on their stable sibling and must not be in the subset.

Usage:
  # Resume specific stable indices (comma-separated or ranges)
  python scripts/resume_timed_out.py \\
    --config-name experiments/swagatam/test_moe_130M_300BT_filtering \\
    --indices 0,3,6,48

  # Dry-run: print commands without executing
  python scripts/resume_timed_out.py ... --dry-run

  # Resume one job at a time
  python scripts/resume_timed_out.py ... --sequential

  # Write commands to a .sh file (for tmux/parallel launch)
  python scripts/resume_timed_out.py ... --output-script resume_commands.sh
  bash resume_commands.sh   # Creates tmux session with one window per job

Each job is resumed with:
  - --array-subset <index>  (run only that sweep point)
  - ++backend.megatron.load=<output_dir>/checkpoints
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PYTHON = Path("/leonardo_work/OELLM_prod2026/users/shaldar0/.conda/llm/bin/python")


def _write_launch_script(
    *,
    commands: list[tuple[int, list[str]]],
    output_path: Path,
    repo_root: Path,
    tmux_session: str,
) -> None:
    """Write a shell script that launches each resume command in a tmux window."""
    script_dir = output_path.resolve().parent
    base = output_path.stem

    lines = [
        "#!/bin/bash",
        "# Resume commands - one tmux window per job",
        f"# Expected: {len(commands)} SLURM job(s) (1 per run_autoexp)",
        "# Generated by resume_timed_out.py",
        "",
        f'SESSION_NAME="{tmux_session}"',
        f'SCRIPT_DIR="{script_dir}"',
        "",
    ]

    # Write each command to a sibling .sh file
    for i, (idx, cmd) in enumerate(commands):
        cmd_path = script_dir / f"{base}_{i}.sh"
        cmd_lines = [
            "#!/bin/bash",
            f'cd "{repo_root}"',
            " ".join(cmd),
        ]
        cmd_path.write_text("\n".join(cmd_lines) + "\n")
        cmd_path.chmod(0o755)

    # Build main script that references the command scripts
    for i, (idx, _) in enumerate(commands):
        cmd_path = script_dir / f"{base}_{i}.sh"
        lines.append(f'CMD_{i}="{cmd_path}"')
    lines.append("")

    # Create tmux session with first window
    idx0, _ = commands[0]
    lines.append(f"# Create session with first job (index {idx0})")
    lines.append(f'tmux new-session -d -s "$SESSION_NAME" -n "idx_{idx0}" "bash \\"$CMD_0\\"; read"')
    lines.append("")

    # Remaining windows
    for i, (idx, _) in enumerate(commands[1:], start=1):
        lines.append(f'tmux new-window -t "$SESSION_NAME" -n "idx_{idx}" "bash \\"$CMD_{i}\\"; read"')

    lines.extend(["", 'tmux attach-session -t "$SESSION_NAME"', ""])
    output_path.write_text("\n".join(lines))
    output_path.chmod(0o755)


def parse_indices(spec: str) -> list[int]:
    indices: list[int] = []
    for token in spec.split(","):
        part = token.strip()
        if not part:
            continue
        if "-" in part:
            start_str, end_str = part.split("-", 1)
            start = int(start_str)
            end = int(end_str)
            if end < start:
                raise ValueError(f"invalid range '{part}'")
            indices.extend(range(start, end + 1))
        else:
            indices.append(int(part))
    return sorted(set(indices))


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--config-name", required=True, help="Config name (e.g. experiments/swagatam/test_moe_130M_300BT_filtering)")
    parser.add_argument("--config-dir", type=Path, default=Path("config"))
    parser.add_argument(
        "--python",
        type=Path,
        default=DEFAULT_PYTHON,
        help=f"Python executable for run_autoexp (default: {DEFAULT_PYTHON})",
    )
    parser.add_argument(
        "--indices",
        default="",
        help="Comma-separated indices or ranges (e.g. 0,1,5-10,48). Use --list-stable to see stable indices.",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print commands without executing")
    parser.add_argument(
        "--sequential",
        action="store_true",
        help="Run jobs one at a time (wait for each to finish before starting next)",
    )
    parser.add_argument(
        "--output-script",
        type=Path,
        metavar="FILE",
        help="Write resume commands to a shell script. Run it to launch all in a tmux session.",
    )
    parser.add_argument(
        "--tmux-session",
        default="resume_jobs",
        help="Tmux session name when using --output-script (default: resume_jobs)",
    )
    parser.add_argument(
        "--list-stable",
        action="store_true",
        help="List all stable indices and exit (useful to see which indices to pass)",
    )
    parser.add_argument(
        "--list-decay",
        action="store_true",
        help="List decay indices with job names (to find index for a failed decay job)",
    )
    parser.add_argument(
        "overrides",
        nargs="*",
        default=[],
        help="Extra Hydra overrides (e.g. ++slurm.sbatch.time=48:00:00)",
    )
    args = parser.parse_args()

    if args.list_stable:
        sys.path.insert(0, str(REPO_ROOT))
        from oellm_autoexp.config.loader import load_config_reference
        from oellm_autoexp.config.schema import ConfigSetup
        from oellm_autoexp.hydra_staged_sweep import expand_sweep

        config_setup = ConfigSetup(
            pwd=str(REPO_ROOT),
            config_name=args.config_name,
            config_dir=str(args.config_dir),
            overrides=args.overrides,
            monitor_state_dir="./monitor_state",
        )
        root = load_config_reference(config_setup=config_setup)
        points = expand_sweep(root.sweep)
        stable = sorted(p.index for p in points if p.parameters.get("stage") == "stable")
        print(f"Stable indices ({len(stable)}): {stable}")
        return

    if args.list_decay:
        sys.path.insert(0, str(REPO_ROOT))
        from oellm_autoexp.config.loader import load_config_reference
        from oellm_autoexp.config.schema import ConfigSetup
        from oellm_autoexp.hydra_staged_sweep import expand_sweep
        from oellm_autoexp.orchestrator import build_execution_plan

        config_setup = ConfigSetup(
            pwd=str(REPO_ROOT),
            config_name=args.config_name,
            config_dir=str(args.config_dir),
            overrides=args.overrides,
            monitor_state_dir="./monitor_state",
        )
        root = load_config_reference(config_setup=config_setup)
        plan = build_execution_plan(root, config_setup=config_setup)
        decay_jobs = [
            (job.config.index, getattr(job.config.job, "base_output_dir", ""))
            for job in plan.jobs
            if getattr(job.config, "stage", "").startswith("decay")
        ]
        print("Decay indices (index -> output_dir):")
        for idx, out_dir in sorted(decay_jobs, key=lambda x: x[0]):
            name = Path(out_dir).name if out_dir else ""
            print(f"  {idx}: {name}")
        return

    try:
        indices = parse_indices(args.indices)
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

    if not indices:
        print("No indices specified. Use --indices or --list-stable to see stable indices.", file=sys.stderr)
        sys.exit(1)

    # Import here so we get proper config resolution
    sys.path.insert(0, str(REPO_ROOT))
    from oellm_autoexp.config.loader import load_config_reference
    from oellm_autoexp.config.schema import ConfigSetup
    from oellm_autoexp.hydra_staged_sweep import expand_sweep
    from oellm_autoexp.orchestrator import build_execution_plan

    config_setup = ConfigSetup(
        pwd=str(REPO_ROOT),
        config_name=args.config_name,
        config_dir=str(args.config_dir),
        overrides=args.overrides,
        monitor_state_dir="./monitor_state",
    )
    root = load_config_reference(config_setup=config_setup)

    # Only stable-stage jobs can be resumed; decay jobs need their stable sibling in the plan
    points = expand_sweep(root.sweep)
    stable_indices = {
        p.index for p in points
        if p.parameters.get("stage") == "stable"
    }
    resume_indices = sorted(set(indices) & stable_indices)
    skipped = sorted(set(indices) - stable_indices)
    if skipped:
        print(
            f"Note: skipping non-stable indices {skipped} (decay jobs cannot be resumed this way)",
            file=sys.stderr,
        )
    if not resume_indices:
        print(
            "No stable indices to resume. Pass only stable-stage indices (e.g. 0,3,6,9,...).",
            file=sys.stderr,
        )
        sys.exit(1)

    plan = build_execution_plan(
        root,
        config_setup=config_setup,
        subset_indices=set(resume_indices),
    )

    # Build index -> (output_dir, job_name) from plan
    index_to_load: dict[int, str] = {}
    for job in plan.jobs:
        cfg = job.config
        idx = getattr(cfg, "index", None)
        if idx is None:
            continue
        base_output = getattr(cfg.job, "base_output_dir", None)
        if not base_output:
            print(f"Warning: no base_output_dir for index {idx}, skipping", file=sys.stderr)
            continue
        load_path = f"{base_output}/checkpoints"
        index_to_load[idx] = load_path

    missing = set(resume_indices) - set(index_to_load)
    if missing:
        print(f"Warning: indices {sorted(missing)} not found in plan (filtered out?)", file=sys.stderr)

    commands: list[tuple[int, list[str]]] = []
    for idx in resume_indices:
        if idx not in index_to_load:
            continue
        load_path = index_to_load[idx]
        cmd = [
            str(args.python),
            str(REPO_ROOT / "scripts" / "run_autoexp.py"),
            "--config-name",
            args.config_name,
            "--config-dir",
            str(args.config_dir),
            "--array-subset",
            str(idx),
            f"++backend.megatron.load={load_path}",
            *args.overrides,
        ]
        commands.append((idx, cmd))

    if not commands:
        print("No valid resume commands to run.", file=sys.stderr)
        sys.exit(1)

    print(f"Resuming {len(commands)} job(s): indices {[c[0] for c in commands]}")
    for idx, cmd in commands:
        print(f"  [{idx}] load={index_to_load[idx]}")

    if args.dry_run:
        for idx, cmd in commands:
            print(f"\n# Index {idx}:")
            print(" ".join(cmd))
        return

    if args.output_script:
        _write_launch_script(
            commands=commands,
            output_path=args.output_script,
            repo_root=REPO_ROOT,
            tmux_session=args.tmux_session,
        )
        print(f"Wrote {args.output_script}")
        print(f"Run: bash {args.output_script}")
        return

    if args.sequential:
        for idx, cmd in commands:
            print(f"\n>>> Resuming index {idx}...")
            rc = subprocess.run(cmd, cwd=REPO_ROOT)
            if rc.returncode != 0:
                print(f"Job {idx} failed with exit code {rc.returncode}", file=sys.stderr)
                sys.exit(rc.returncode)
        print("\nAll jobs completed.")
        return

    # Parallel: run each in background (each has its own monitor)
    print("\nSubmitting jobs (each runs in foreground with its own monitor)...")
    print("Run each command in a separate terminal/screen, or use --sequential to run one by one.\n")
    for idx, cmd in commands:
        print(f"# Index {idx}:")
        print(" ".join(cmd))
        print()
    print("Copy-paste the commands above into separate terminals, or run with --sequential.")


if __name__ == "__main__":
    main()
