#!/usr/bin/env python3
"""Analyze low-throughput iterations for all runs in a multilingual scaling
experiment directory.

For each run (possibly spanning multiple Slurm jobs / restarts), reports:
  - time lost in low-throughput iterations (hours)
  - GPU-hours lost due to low-throughput iterations

Low-throughput is defined as throughput < 30% of the run-average (average computed
from iterations after skipping warmup and excluding extreme outliers).

The total GPU hours for a run come from <training_dir>/gpu_hours.csv; if that file is
absent it is regenerated by running gpu_hours.py.

Usage:
    python low_throughput_analysis.py <experiment_dir> [--csv out.csv]
    # e.g.: python low_throughput_analysis.py /home/diana/mn5/multilingual_scaling/0.1B_ne
"""

import argparse
import csv
import re
import subprocess
import sys
from pathlib import Path
from statistics import mean

# Allow importing sibling modules when run as a script.
_tools_dir = str(Path(__file__).parent)
if _tools_dir not in sys.path:
    sys.path.insert(0, _tools_dir)

from megatron_throughput_from_logs import load_or_compute_throughput

# ── Constants ─────────────────────────────────────────────────────────────────

LOW_THROUGHPUT_FRACTION = 0.30

# ── Regex patterns ────────────────────────────────────────────────────────────

RE_ITER = re.compile(
    r"iteration\s+(\d+)/\s*(\d+)\s*\|"
    r".*?elapsed time per iteration \(ms\):\s*([\d.]+)"
    r".*?throughput per GPU \(TFLOP/s/GPU\):\s*([\d.]+)",
    re.DOTALL,
)

RE_SBATCH_NODES = re.compile(r"^#SBATCH\s+--nodes[= ](\d+)", re.MULTILINE)
RE_SBATCH_GPUS_NODE = re.compile(r"^#SBATCH\s+--gpus-per-node[= ](\d+)", re.MULTILINE)
RE_SBATCH_GRES = re.compile(r"^#SBATCH\s+--gres=gpu[^:\n]*:(\d+)", re.MULTILINE)


# ── Helpers ───────────────────────────────────────────────────────────────────


def _parse_log_iterations(log_path: Path) -> list[tuple[int, float, float]]:
    """Return sorted list of (iter_num, elapsed_ms, tflop_per_gpu) from a
    stdout log."""
    if not log_path.is_file():
        return []
    text = log_path.read_text(errors="replace")
    rows: list[tuple[int, float, float]] = []
    for m in RE_ITER.finditer(text):
        rows.append((int(m.group(1)), float(m.group(3)), float(m.group(4))))
    rows.sort(key=lambda x: x[0])
    return rows


def _parse_sbatch_gpus(run_dir: Path) -> int | None:
    """Return total GPU count (nodes × gpus-per-node) from job.sbatch, or
    None."""
    sbatch = run_dir / "job.sbatch"
    if not sbatch.is_file():
        return None
    text = sbatch.read_text(errors="replace")
    nodes = gpus_per_node = None
    m = RE_SBATCH_NODES.search(text)
    if m:
        nodes = int(m.group(1))
    m = RE_SBATCH_GPUS_NODE.search(text)
    if m:
        gpus_per_node = int(m.group(1))
    if gpus_per_node is None:
        m = RE_SBATCH_GRES.search(text)
        if m:
            gpus_per_node = int(m.group(1))
    if nodes is not None and gpus_per_node is not None:
        return nodes * gpus_per_node
    return None


def _get_gpus_from_csv(run_name: str, gpu_hours_csv: Path) -> int | None:
    """Return GPU count for *run_name* from gpu_hours.csv (first non-zero
    entry)."""
    if not gpu_hours_csv.is_file():
        return None
    with gpu_hours_csv.open(newline="") as f:
        for row in csv.DictReader(f):
            if row.get("experiment") == run_name and row.get("gpus"):
                try:
                    v = int(row["gpus"])
                    if v > 0:
                        return v
                except (ValueError, TypeError):
                    pass
    return None


def _ensure_gpu_hours_csv(training_dir: Path) -> Path:
    """Return gpu_hours.csv path, generating it via gpu_hours.py if the file is
    absent."""
    csv_path = training_dir / "gpu_hours.csv"
    if csv_path.is_file():
        return csv_path
    gpu_hours_script = Path(__file__).parent / "gpu_hours.py"
    if gpu_hours_script.is_file():
        print("[info] gpu_hours.csv not found — generating via gpu_hours.py ...", flush=True)
        try:
            subprocess.run(
                [
                    sys.executable,
                    str(gpu_hours_script),
                    str(training_dir),
                    "--output",
                    str(csv_path),
                ],
                check=True,
                timeout=120,
            )
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as exc:
            print(f"[warn] gpu_hours.py failed: {exc}", file=sys.stderr)
    return csv_path


# ── Core analysis ─────────────────────────────────────────────────────────────


def analyze_job(
    log_path: Path,
    num_gpus: int | None = None,
    max_elapsed_ms: float = 6000.0,
    skip_first_iters: int = 50,
    max_iters_used: int = 500,
) -> dict:
    """Analyze low-throughput iterations for a single Slurm job log file.

    The reference average is obtained via :func:`load_or_compute_throughput`
    (shared with progress_tracker) and cached in ``<run_dir>/throughput/``.
    Low-throughput detection scans *all* iterations in the log (no elapsed-time
    filter) so that genuine stall events are always counted.

    Args:
        log_path:        Path to a stdout-{jobid}.log file.
        num_gpus:        GPU count for this job (used to compute gpu_h_lost).
        max_elapsed_ms:  Elapsed-time ceiling used when computing the reference
                         average (passed to load_or_compute_throughput).
        skip_first_iters: Warmup iterations excluded from the average.
        max_iters_used:  Maximum post-warmup iterations averaged.

    Returns a dict with keys:
        time_lost_h  – total elapsed time in low-throughput iters (hours)
        gpu_h_lost   – GPU-hours lost in low-throughput iters
        n_low_iters  – count of flagged iterations
        avg_tflop    – reference average throughput (TFLOP/s/GPU)
        num_gpus     – GPU count used for the calculation
    """
    empty = {
        "time_lost_h": None,
        "gpu_h_lost": None,
        "n_low_iters": None,
        "avg_tflop": None,
        "num_gpus": num_gpus,
    }

    throughput = load_or_compute_throughput(
        log_path, max_elapsed_ms, skip_first_iters, max_iters_used
    )
    if throughput is None:
        return empty

    avg_tflop = throughput["avg_tflop_per_gpu"]
    threshold = avg_tflop * LOW_THROUGHPUT_FRACTION

    # Scan ALL iterations (no elapsed-time filter) to count and time low-TP events.
    # Skip the first skip_first_iters so they are not double-counted with TTFI:
    # TTFI is measured from job start through the timestamp of the first logged
    # iteration, which includes the wall time of those warmup iters.
    rows = _parse_log_iterations(log_path)
    if not rows:
        return empty

    rows_post_warmup = [(it, et, tflop) for it, et, tflop in rows if it > skip_first_iters]
    low_elapsed_ms = sum(et for _it, et, tflop in rows_post_warmup if tflop < threshold)
    n_low = sum(1 for _it, _et, tflop in rows_post_warmup if tflop < threshold)

    time_lost_h = low_elapsed_ms / 1_000 / 3_600
    gpu_h_lost = (time_lost_h * num_gpus) if num_gpus is not None else None

    return {
        "time_lost_h": time_lost_h,
        "gpu_h_lost": gpu_h_lost,
        "n_low_iters": n_low,
        "avg_tflop": avg_tflop,
        "num_gpus": num_gpus,
    }


def analyze_run(
    run_dir: Path,
    run_name: str,
    gpu_hours_csv: Path | None = None,
    num_gpus: int | None = None,
    max_elapsed_ms: float = 6000.0,
    skip_first_iters: int = 50,
    max_iters_used: int = 500,
) -> dict:
    """Analyze low-throughput iterations for a whole run (all jobs aggregated).

    Calls analyze_job per log file and sums the results. Used by the standalone
    CLI; progress_tracker calls analyze_job directly per Slurm job.

    Args:
        run_dir:          Path to the run directory (contains logs/).
        run_name:         Experiment name (matches gpu_hours.csv 'experiment' column).
        gpu_hours_csv:    Path to gpu_hours.csv (used for GPU count fallback).
        num_gpus:         GPU count override; if None, derived from sbatch or csv.
        max_elapsed_ms:   Passed to analyze_job / load_or_compute_throughput.
        skip_first_iters: Warmup iterations excluded from the reference average.
        max_iters_used:   Maximum post-warmup iterations averaged.
    """
    empty = {
        "time_lost_h": None,
        "gpu_h_lost": None,
        "n_low_iters": None,
        "avg_tflop": None,
        "num_gpus": None,
    }

    logs_dir = run_dir / "logs"
    if not logs_dir.is_dir():
        return empty

    log_files = sorted(logs_dir.glob("stdout-*.log"))
    if not log_files:
        return empty

    if num_gpus is None:
        num_gpus = _parse_sbatch_gpus(run_dir)
    if num_gpus is None and gpu_hours_csv is not None:
        num_gpus = _get_gpus_from_csv(run_name, gpu_hours_csv)

    total_time_lost_h = 0.0
    total_gpu_h_lost = 0.0
    total_n_low = 0
    avg_tflops: list[float] = []
    any_data = False

    for log_file in log_files:
        job_stats = analyze_job(
            log_file,
            num_gpus=num_gpus,
            max_elapsed_ms=max_elapsed_ms,
            skip_first_iters=skip_first_iters,
            max_iters_used=max_iters_used,
        )
        if job_stats["time_lost_h"] is None:
            continue
        any_data = True
        total_time_lost_h += job_stats["time_lost_h"]
        if job_stats["gpu_h_lost"] is not None:
            total_gpu_h_lost += job_stats["gpu_h_lost"]
        total_n_low += job_stats["n_low_iters"] or 0
        if job_stats["avg_tflop"] is not None:
            avg_tflops.append(job_stats["avg_tflop"])

    if not any_data:
        return empty

    return {
        "time_lost_h": total_time_lost_h,
        "gpu_h_lost": total_gpu_h_lost if num_gpus is not None else None,
        "n_low_iters": total_n_low,
        "avg_tflop": mean(avg_tflops) if avg_tflops else None,
        "num_gpus": num_gpus,
    }


# ── Directory-level analysis ──────────────────────────────────────────────────


def analyze_experiment_dir(
    experiment_dir: Path,
    max_elapsed_ms: float = 6000.0,
    skip_first_iters: int = 50,
    max_iters_used: int = 500,
) -> list[dict]:
    """Analyze all runs under <experiment_dir>/training/.

    Returns a list of dicts, one per run, each containing run_name plus
    all keys returned by analyze_run().
    """
    training_dir = experiment_dir / "training"
    if not training_dir.is_dir():
        print(f"[error] No training/ directory found under {experiment_dir}", file=sys.stderr)
        return []

    gpu_hours_csv = _ensure_gpu_hours_csv(training_dir)

    results: list[dict] = []
    for run_dir in sorted(training_dir.iterdir()):
        if not run_dir.is_dir():
            continue
        run_name = run_dir.name
        stats = analyze_run(
            run_dir,
            run_name,
            gpu_hours_csv,
            max_elapsed_ms=max_elapsed_ms,
            skip_first_iters=skip_first_iters,
            max_iters_used=max_iters_used,
        )
        stats["run_name"] = run_name
        results.append(stats)

    return results


# ── CLI ───────────────────────────────────────────────────────────────────────


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Report time and GPU-hours lost in low-throughput iterations."
    )
    ap.add_argument(
        "experiment_dir",
        help="Experiment directory, e.g. /home/diana/mn5/multilingual_scaling/0.1B_ne",
    )
    ap.add_argument("--csv", default=None, help="Optional output CSV path")
    ap.add_argument(
        "--fraction",
        type=float,
        default=LOW_THROUGHPUT_FRACTION,
        help="Low-throughput threshold as a fraction of average (default: 0.30)",
    )
    ap.add_argument(
        "--max-elapsed-ms",
        type=float,
        default=6000.0,
        help="Drop iterations longer than this when computing the reference average (default: 6000)",
    )
    ap.add_argument(
        "--skip-first-iters",
        type=int,
        default=50,
        help="Warmup iterations excluded from the reference average (default: 50)",
    )
    ap.add_argument(
        "--max-iters",
        type=int,
        default=500,
        help="Maximum post-warmup iterations used for the reference average (default: 500)",
    )
    args = ap.parse_args()

    exp_dir = Path(args.experiment_dir)
    if not exp_dir.is_dir():
        print(f"[error] Directory not found: {exp_dir}", file=sys.stderr)
        sys.exit(1)

    results = analyze_experiment_dir(
        exp_dir,
        max_elapsed_ms=args.max_elapsed_ms,
        skip_first_iters=args.skip_first_iters,
        max_iters_used=args.max_iters,
    )
    if not results:
        print("No runs found.")
        return

    W = max(len(r["run_name"]) for r in results) + 2

    header = (
        f"{'Run':<{W}}  {'LowTP-Iters':>12}  {'AvgTFLOP':>9}"
        f"  {'TimeLost(h)':>12}  {'GPU-h Lost':>11}  {'GPUs':>5}"
    )
    sep = "─" * len(header)
    print(sep)
    print(header)
    print(sep)

    for r in results:
        n_str = str(r["n_low_iters"]) if r["n_low_iters"] is not None else "N/A"
        avg_str = f"{r['avg_tflop']:.1f}" if r["avg_tflop"] is not None else "N/A"
        tl_str = f"{r['time_lost_h']:.4f}" if r["time_lost_h"] is not None else "N/A"
        gl_str = f"{r['gpu_h_lost']:.4f}" if r["gpu_h_lost"] is not None else "N/A"
        gpus_str = str(r["num_gpus"]) if r["num_gpus"] is not None else "N/A"

        print(
            f"{r['run_name']:<{W}}  {n_str:>12}  {avg_str:>9}"
            f"  {tl_str:>12}  {gl_str:>11}  {gpus_str:>5}"
        )

    print(sep)

    if args.csv:
        csv_path = Path(args.csv)
        fields = ["run_name", "avg_tflop", "n_low_iters", "time_lost_h", "gpu_h_lost", "num_gpus"]
        with csv_path.open("w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
            writer.writeheader()
            writer.writerows(results)
        print(f"\nWrote {len(results)} rows to {csv_path}")


if __name__ == "__main__":
    main()
