type: product
groups:
  - type: list
    configs:
      - job.name: "qwen3_dense_8b_training_scale_nodes\\${slurm.sbatch.nodes}_mbsz\\${backend.megatron.micro_batch_size}_gbsz\\${backend.megatron.global_batch_size}_profiling"
        backend.megatron.wandb_exp_name: "\\${job.name}"
  - type: list
    configs:
      - backend.megatron.use_torch_fsdp2: False
        backend.megatron.tensor_model_parallel_size: 2
        backend.megatron.sequence_parallel: True
        backend.megatron.use_distributed_optimizer: True
        slurm.sbatch.qos: acc_debug
        slurm.env.CUDA_DEVICE_MAX_CONNECTIONS: 1
  - type: product
    params:
      backend.megatron.micro_batch_size: [1]
      backend.megatron.global_batch_size: [512]
      slurm.sbatch.nodes: [4]
  - type: list
    configs:
      - stage: throughput
        backend.megatron.train_iters: 10000
        backend.megatron.lr_wsd_decay_iters: 0
        backend.megatron.lr_warmup_iters: 0
        backend.megatron.save_interval: 999999999
        backend.megatron.aux.save_step_0: 999999999
