name: Pre-commit hooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit_hooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit ruff

      - name: Check code with ruff
        run: |
          ruff check --fix

      - name: Format code with ruff
        run: |
          ruff format --diff

      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files
